substitutions:
  devicename: buffet
  upper_devicename: Buffet
  
esphome:
  name: $devicename
  # friendly_name: $upper_devicename

esp8266:
  board: esp8285
  early_pin_init: False

logger:

api:
  encryption:
    key: "6jY9XvV9ISORvZnkASlBab7yGzkFQlP7bdDIOpjSwek="

ota:
  password: "6ffc4a404a316cac96dbcc8a6bbe2630"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  ap:
    ssid: "$upper_devicename Fallback Hotspot"
    password: !secret ap_password

captive_portal:

# web_server:

output:
  - platform: esp8266_pwm
    id: red_output
    pin: GPIO4
  - platform: esp8266_pwm
    id: green_output
    pin: GPIO12
  - platform: esp8266_pwm
    id: blue_output
    pin: GPIO14
  - platform: esp8266_pwm
    id: warm_white_output
    pin: GPIO13
  - platform: esp8266_pwm
    id: white_output
    pin: GPIO5

light:
  - platform: rgbww
    name: $upper_devicename
    id: $devicename
    restore_mode: ALWAYS_OFF
    red: red_output
    green: green_output
    blue: blue_output
    warm_white: warm_white_output
    cold_white: white_output
    cold_white_color_temperature: 6000 K
    warm_white_color_temperature: 3000 K
    color_interlock: true
    default_transition_length: 100ms
    on_turn_on:
      then:
        - light.turn_on:
            id: $devicename
            brightness: 100%
            red: 100%
            green: 0%
            blue: 100%


binary_sensor:
  - platform: status
    name: "$upper_devicename Status"

sensor:
  - platform: wifi_signal
    name: "$upper_devicename WiFi Signal dB"
    id: wifi_signal_db
    update_interval: 60s
    entity_category: "diagnostic"

  - platform: copy
    source_id: wifi_signal_db
    name: "$upper_devicename WiFi Signal Percent"
    filters:
      - lambda: return min(max(2 * (x + 100.0), 0.0), 100.0);
    unit_of_measurement: "%"
    entity_category: "diagnostic"

  - platform: uptime
    name: $upper_devicename Uptime Sensor

text_sensor:
  - platform: wifi_info
    ip_address:
      name: "$upper_devicename IP Address"

  - platform: version
    name: "$upper_devicename ESPHome Version"

button:
  - platform: factory_reset
    name: $upper_devicename Factory Reset

  - platform: restart
    name: $upper_devicename Restart

time:
  - platform: sntp
    id: sntp_time